name: aether_file
description: "Naqa - Luxury Offline Smart File & Photo Organizer"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  permission_handler: ^11.3.1     # لطلب تصاريح الوصول لملفات وصور الجوال
  storage_space: ^0.2.1          # لقراءة سعة الذاكرة الداخلية الحقيقية للجوال
  path_provider: ^2.1.2          # للوصول لمسارات النظام المحلية
  intl: ^0.19.0                  # لتنسيق أحجام الملفات والتوارخ

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: IBMPlexSansArabic
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSansArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSansArabic-Bold.ttf
          weight: 700
